ENEMY = 3
POP_SIZE = 100  # 300
GENERATIONS = 200  # 200
OVERRIDE = True

# TWEAK:
MIN_MUTATION = 0.01  # minimum value of mutation
TOURNAMENT_K = int(0.05*POP_SIZE)  # 0.05
LOWER_CAUCHY = -2
UPPER_CAUCHY = 2
DOOMSDAY_GENS = int(0.1*GENERATIONS)
DOOMSDAY = 0.333  # 0.333 -> make 0.2, PART OF POPULATION THAT GETS DESTROYED DURING RESHUFFLE
MAX_DIFF_STABLE = 5

MUTATION_DELTA = 1/(0.5*GENERATIONS)

# ENEMY-POPSIZE-DOOMSDAYGENS-DOOMSDAY-MINMUTATION-TOURNAMENTK-LOWERCAUCHY-UPPERCAUCHY-MAX-DIFFSTABLE-MUTATIONDELTA
