ENEMY = 2
POP_SIZE = 300  # 300
GENERATIONS = 200  # 200

# TWEAK:
MIN_MUTATION = 0.01  # minimum value of mutation, max = MAX_CROSSOVER-MIN_MUTATION
MAX_CROSSOVER = 0.8
TOURNAMENT_K = int(0.075*POP_SIZE)  # 0.075
LOWER_CAUCHY = -2
UPPER_CAUCHY = 2
DOOMSDAY_GENS = int(1.5*GENERATIONS)
DOOMSDAY = 0.01  # Doomsday is turned off currently
MAX_DIFF_STABLE = 5

MUTATION_DELTA = 1/(0.5*GENERATIONS)

# ENEMY-POPSIZE-DOOMSDAYGENS-DOOMSDAY-MINMUTATION-TOURNAMENTK-LOWERCAUCHY-UPPERCAUCHY-MAX-DIFFSTABLE-MUTATIONDELTA
SAVE_HEALTH = True # dump player and enemy health