POP_SIZE = 100
GENERATIONS = 150

# TWEAK:
MIN_MUTATION = 0.005  # minimum value of mutation
TOURNAMENT_K = 10
LOWER_CAUCHY = -2
UPPER_CAUCHY = 2
DOOMSDAY_GENS = 20
DOOMSDAY = 0.1  # PART OF POPULATION THAT GETS DESTROYED DURING RESHUFFLE
MAX_DIFF_STABLE = 2
ENEMY = 4

MUTATION_DELTA = 1/(0.333*GENERATIONS)
