# Weights
N_HIDDEN_NEURONS = 10
LIM_UPPER = 1
LIM_LOWER = -1

# Simple EA
MUTATION_PROB = 0.1  # TODO
CROSSOVER_PROB = 0.1  # TODO

# Island EA
NUM_ISLANDS = 2
NUM_ENEMIES = 2
assert NUM_ENEMIES <= 8
EPOCH = 2  # TODO
GENS_TOGETHER_START = 3
GENS_ISLAND = 5
assert GENS_ISLAND >= EPOCH
GENS_TOGETHER_END = 3
NUM_MIGRATION = 1  # TODO: number of individuals that each island EA sends to the other EAs

# General
POP_SIZE = 50
assert POP_SIZE % NUM_ISLANDS == 0
assert int(POP_SIZE / NUM_ISLANDS) >= NUM_MIGRATION
NUM_GENS_OVERALL = GENS_TOGETHER_START + GENS_ISLAND + GENS_TOGETHER_END
ENEMIES = [1, 2, 3, 4, 5]
assert len(ENEMIES) >= NUM_ENEMIES
